
INSERT INTO users ( username, password, email) VALUES ( 'andrea.cerrato', 'gamma', 'andrea.cerrato@edu-its.it') ;
INSERT INTO users ( username, password, email) VALUES ( 'andrea.lergo', 'gamma', 'andrea.lergo@edu-its.it') ;


INSERT INTO books (title, author, image, summary, year, pages) VALUES ('Il Nome della Rosa', 'Umberto Eco', 'il_nome_della_rosa.jpg', 'Un’abbazia medievale isolata. Una comunità di monaci sconvolta da una serie di delitti. Un frate francescano che indaga i misteri di una biblioteca inaccessibile.In una edizione con i disegni e gli appunti preparatori dell’autore, il romanzo che ha rivelato il genio narrativo di Umberto Eco: tradotto in 60 paesi con oltre 50 milioni di copie vendute, Il nome della rosa ha vinto il premio Strega nel 1981 e ha ispirato un film e una serie tv di successo mondiale. “ I disegni e le annotazioni manoscritte del futuro autore del Nome della rosa testimoniano il minuzioso lavoro preparatorio prima della stesura del romanzo. A conferma di quanto affermato da Eco nelle ‘Postille’ (1983): ‘Per raccontare bisogna anzitutto costruirsi un mondo il più possibile ammobiliato sino agli ultimi particolari.’ E che cosa ci racconta o, meglio, ci anticipa di questo mondo il materiale visivo qui riprodotto? Innanzi tutto l’identità, la fisionomia dei principali protagonisti, con il tipico tratto veloce, arguto dell’autore, che ne giustificherà l’invenzione ‘per sapere quali parole mettere loro in bocca.’ Poi profili e piante di abbazie, castelli, labirinti, in una piena immersione nella cultura anche materiale del Medioevo.” Mario Andreose', '1980', '624');
INSERT INTO books (title, author, image, summary, year, pages) VALUES ('1984', 'George Orwell', '1984.jpg', '1984 è il più celebre romanzo di George Orwell ed è stato scritto nel 1948. Una guerra devastante ha suddiviso il pianeta in tre super-potenze, in lotta fra loro e governate da regimi totalitari: Oceania, Eurasia ed Estasia. È nella prima che Winston vive e lavora da uomo qualunque. Nell''animo, però, sembra l''unico a rifiutare la società voluta dal Partito e la filosofia imposta, che non permette tanto l''amore quanto il libero pensiero. La sua ribellione è interiore, ma col tempo si concretizza in azioni sempre più pericolose. La sua vita viene stravolta quando incontra Julia, una ragazza che solo in apparenza sembra calata nelle logiche del sistema… "1984" è un romanzo di grande importanza e attualità. Ammonisce contro ogni forma di totalitarismo, di falsificazione della realtà e della storia, corrotta dai mezzi d''informazione, e contro l''annullamento dell''identità individuale. Significativa è la traduzione italiana di "Big Brother" (fratello maggiore) che ormai è rimasta nel nostro immaginario come quella di "Grande Fratello".', '1948', '320');
INSERT INTO books (title, author, image, summary, year, pages) VALUES ('La Divina Commedia', 'Dante Alighieri', 'divina_commedia.jpg', 'L’opera è divisa in tre parti: Inferno, Purgatorio e Paradiso, ciascuna composta di trentatré canti. Ad accompagnare Dante nella straordinaria discesa all’Inferno e nella salita al Purgatorio è il poeta latino Virgilio, che riveste il ruolo di guida spirituale. I personaggi che i due incontrano nei gironi infernali, dannati dalle colpe sempre più gravi, appartengono non solo alla storia e alla mitologia, ma sono anche contemporanei dell’autore, che non esita a condannare i mali del tempo, e in particolare la corruzione di clero e papato. Per questo motivo La Divina Commedia è considerata anche un’opera politica. Nel Purgatorio, rappresentato come una montagna, si trovano invece coloro che nel corso della vita compirono peccati più lievi; per questo l’atmosfera è più serena, intrisa di speranza, e anche l’anima di Dante, nel corso della salita, si alleggerisce del peso delle sue colpe. Nel Paradiso Dante incontra l’amata Beatrice, che lo conduce attraverso i cieli dei pianeti e delle stelle fisse, tra angeli, santi e beati, fino al cospetto di Dio, in un crescendo di luminosità e di purificazione.', '1300', '1000');
INSERT INTO books (title, author, image, summary, year, pages) VALUES ('Il Grande Gatsby', 'Francis Scott Fitzgerald', 'The_Great_Gatsby.jpg', 'Il romantico ed enigmatico Jay Gatsby organizza feste sontuose nella speranza di avvicinare la donna amata in gioventù, Daisy, che ha sposato un uomo ricco e rozzo. Ne diventerà l''amante, ma un incidente automobilistico darà una tragica svolta al loro amore. Una descrizione spietata e partecipe del mondo fastoso e frivolo degli anni Venti nelle pagine indimenticabili dello scrittore simbolo della generazione perduta.', '1925', '400 ');
INSERT INTO books (title, author, image, summary, year, pages) VALUES ('Carrie', 'Stephen King', 'carrie.jpg', 'Carrie è un''adolescente prigioniera del delirio fanatico della madre e presa di mira dai compagni, però ha un dono. Può muovere gli oggetti con il potere della mente. Le porte si chiudono. Le candele si spengono. Un potere che è anche una condanna. E quando, inaspettato, arriva un atto di gentilezza da una delle sue compagne di classe, un''occasione di normalità in una vita molto diversa da quella dei suoi coetanei, Carrie spera finalmente in un cambiamento. Ma ecco che il sogno si trasforma in un incubo, ciò che sembrava un dono diventa un''arma di sangue e distruzione e scatena una serie di eventi che nessuno potrà mai dimenticare. Torna il primo romanzo del maestro del terrore che ha ispirato due film: il primo del 1976, per la regia di Brian De Palma, con Sissy Spacek; il secondo di Kimberly Peirce, nel 2013, con Julianne Moore nel ruolo della madre di Carrie.', '1985', '224');
INSERT INTO books (title, author, image, summary, year, pages) VALUES ('Shining', 'Stephen King', 'shining.jpg', 'L''Overlook, uno strano e imponente albergo che domina le alte montagne del Colorado, è stato teatro di numerosi delitti e suicidi e sembra aver assorbito forze maligne che vanno al di là di ogni comprensione umana e si manifestano soprattutto d''inverno, quando l''albergo chiude e resta isolato per la neve. Uno scrittore fallito, Jack Torrance, con la moglie Wendy e il figlio Danny di cinque anni, accetta di fare il guardiano invernale all''Overlook, ed è allora che le forze del male si scatenano con rinnovato impeto: la famiglia si trova avvolta ben presto in un''atmosfera sinistra. Dinanzi a Danny, dotato di un potere extrasensoriale, si materializzano gli orribili fatti accaduti nelle stanze dell''albergo, ma mentre il bambino si oppone con forza a insidie e presenze, il padre ne cade vittima. Un romanzo che ha appassionato milioni di lettori nel mondo, da cui Stanley Kubrick ha tratto l''omonimo capolavoro cinematografico con Jack Nicholson, Shelley Duvall e Danny Lloyd.', '1978', '560');
INSERT INTO books (title, author, image, summary, year, pages) VALUES ('I Pilastri della Terra', 'Ken Follett', 'pilastri.jpg', 'Un mystery, una storia d''amore, una grande rievocazione storica: nella sua opera più ambiziosa e acclamata, Ken Follett tocca una dimensione epica, trasportandoci nell''Inghilterra medievale al tempo della costruzione di una cattedrale gotica. Intreccio, azione e passioni si sviluppano così sullo sfondo di un''era ricca di intrighi e cospirazioni, pericoli e minacce, guerre civili, carestie, conflitti religiosi e lotte per la successione al trono. Con la stessa suspense che caratterizza tutti i suoi thriller, Follett ricrea un''epoca scomparsa e affascinante. Foreste, castelli e monasteri sono l''avvolgente paesaggio, mosso dai ritmi della vita quotidiana e dalla pressione di eventi storici e naturali entro il quale per circa quarant''anni si confrontano e si scontrano le segrete aspirazioni e i sentimenti dei protagonisti - monaci, mercanti, artigiani, nobili, fanciulle misteriose -, vittime o pedine di avvenimenti che ne segnano i destini e rimettono continuamente in discussione la costruzione della cattedrale.', '2007', '1030');
INSERT INTO books (title, author, image, summary, year, pages) VALUES ('Dieci piccoli indiani', 'Agatha Christie', '10_piccoli_indiani.jpg', 'Una casa misteriosa su un''isola deserta, lontana dal resto del mondo. Dieci persone che non si sono mai conosciute prima, tutte accomunate da un inquietante passato, riunite sotto lo stesso tetto da una serie inspiegabile di inviti. Un''assurda filastrocca per bambini che ritorna ossessivamente, scandendo in maniera implacabile, come in un incubo, una serie di omicidi. Pubblicato per la prima volta nel 1939, "Dieci piccoli indiani" è il capolavoro della Christie, uno dei massimi esempi di giallo classico.', '1939', '256');
INSERT INTO books (title, author, image, summary, year, pages) VALUES ('Gomorra', 'Roberto Saviano', 'gomorra.jpg', 'Un libro che racconta il potere della camorra, la sua affermazione economica e finanziaria, e la sua potenza militare, la sua metamorfosi in comitato d''affari. Una scrittura in prima persona fatta dal luogo degli agguati, nei negozi e nelle fabbriche dei clan, raccogliendo testimonianze e leggende. La storia parte dalla guerra di Secondigliano, dall''ascesa del gruppo Di Lauro al conflitto interno che ha generato 80 morti in poco più di un mese. Una narrazione-reportage che svela i misteri del Sistema (così gli affiliati parlano della camorra, termine che nessuno più usa), di un''organizzazione poco conosciuta, creduta sconfitta e che nel silenzio è diventata potentissima superando Cosa Nostra per numero di affiliati e giro d''affari.', '2006', '336');
INSERT INTO books (title, author, image, summary, year, pages) VALUES ('Orgoglio e Pregiudizio', 'Jane Austen', 'orgoglio.jpg', 'Jane Austen fa un ritratto preciso di quelli che erano i modi di vivere, le relazioni, i desideri delle sorelle Bennet, cinque ragazze in età da marito, che vivevano nella campagna inglese del Settecento. La protagonista vera di questo romanzo è però l''ironia, che delinea il carattere degli interpreti, che spesso, loro malgrado, risultano molto divertenti. Non manca naturalmente una coinvolgente e contrastata storia d''amore, perno centrale del romanzo, tra la bella e arguta Elisabeth e il ricchissimo e orgoglioso Mr Darcy. Intorno a loro, personaggi indimenticabili ai quali sarà difficile non affezionarsi.', '1813', '432');
INSERT INTO books (title, author, image, summary, year, pages) VALUES ('Il Trono di Spade', 'George R.R. Martin', 'il_trono.jpg', 'Apophys, il serpente gigante, dio del caos, sta per essere liberato dalle forze del male. Vuole distruggere il mondo e per questo è determinato a inghiottire il dio sole, Ra, il più antico e potente degli dei egizi. Il mito vuole che Ra, minacciato da Apophys e Isis, abbia lasciato il suo trono di fuoco a Osiris e si sia lasciato cadere in un sonno eterno. Per non essere svegliato ha diviso in tre parti il Libro di Ra, un antico papiro che contiene i suoi segreti e le formule magiche per svegliarlo. Sadie e Carter Kane, figli di Julius, egittologo di fama mondiale, scoprono casualmente il terribile rischio che corre il nostro mondo e decidono di partire in cerca di Ra, l''unica speranza di salvezza, il solo dio che sia mai stato in grado di sconfiggere Apophys. Ma prima i fratelli Kane devono recuperare le tre parti del Libro di Ra per ricomporle... e riuscirci non sarà uno scherzo!', '2018', '496');
INSERT INTO books (title, author, image, summary, year, pages) VALUES ('Il codice Da Vinci', 'Dan Brown', 'codice.jpg', 'Quando il curatore del Louvre, Jacques Saunière, viene assassinato, l’ultimo enigma che lascia dietro di sé conduce a un nome: Robert Langdon. Il celebre professore di simbologia di Harvard viene convocato sulla scena del crimine, ma ben presto si rende conto di essere il principale sospettato. Affiancato dalla crittologa Sophie Neveu, nipote della vittima, Langdon inizia una disperata corsa contro il tempo tra Parigi e Londra. Il loro viaggio si snoda attraverso codici nascosti nelle opere di Leonardo da Vinci, antiche società segrete e un mistero legato al Santo Graal, capace di sconvolgere la storia del Cristianesimo. Ogni scoperta li avvicina alla verità, ma li espone a pericoli mortali. Un thriller denso di enigmi e colpi di scena, che ha conquistato milioni di lettori e ridefinito il genere del thriller storico.', '2005', '592');

INSERT INTO users_books (user_id, book_id, read) VALUES (1, 1, true);
INSERT INTO users_books (user_id, book_id, read) VALUES (1, 2, true);
INSERT INTO users_books (user_id, book_id, read) VALUES (1, 3, false);

commit;


