INSERT INTO users ( username, password, email) VALUES ( 'andrea.cerrato', 'gamma', 'andrea.cerrato@edu-its.it') ;

INSERT INTO books (title, author, image, summary, year, pages) VALUES ('Il Nome della Rosa', 'Umberto Eco', 'il_nome_della_rosa.jpg', 'Un’abbazia medievale isolata. Una comunità di monaci sconvolta da una serie di delitti. Un frate francescano che indaga i misteri di una biblioteca inaccessibile.In una edizione con i disegni e gli appunti preparatori dell’autore, il romanzo che ha rivelato il genio narrativo di Umberto Eco: tradotto in 60 paesi con oltre 50 milioni di copie vendute, Il nome della rosa ha vinto il premio Strega nel 1981 e ha ispirato un film e una serie tv di successo mondiale. “ I disegni e le annotazioni manoscritte del futuro autore del Nome della rosa testimoniano il minuzioso lavoro preparatorio prima della stesura del romanzo. A conferma di quanto affermato da Eco nelle ‘Postille’ (1983): ‘Per raccontare bisogna anzitutto costruirsi un mondo il più possibile ammobiliato sino agli ultimi particolari.’ E che cosa ci racconta o, meglio, ci anticipa di questo mondo il materiale visivo qui riprodotto? Innanzi tutto l’identità, la fisionomia dei principali protagonisti, con il tipico tratto veloce, arguto dell’autore, che ne giustificherà l’invenzione ‘per sapere quali parole mettere loro in bocca.’ Poi profili e piante di abbazie, castelli, labirinti, in una piena immersione nella cultura anche materiale del Medioevo.” Mario Andreose', '1980', '624');
INSERT INTO books (title, author, image, summary, year, pages) VALUES ('1984', 'George Orwell', '1984.jpg', '1984 è il più celebre romanzo di George Orwell ed è stato scritto nel 1948. Una guerra devastante ha suddiviso il pianeta in tre super-potenze, in lotta fra loro e governate da regimi totalitari: Oceania, Eurasia ed Estasia. È nella prima che Winston vive e lavora da uomo qualunque. Nell''animo, però, sembra l''unico a rifiutare la società voluta dal Partito e la filosofia imposta, che non permette tanto l''amore quanto il libero pensiero. La sua ribellione è interiore, ma col tempo si concretizza in azioni sempre più pericolose. La sua vita viene stravolta quando incontra Julia, una ragazza che solo in apparenza sembra calata nelle logiche del sistema… "1984" è un romanzo di grande importanza e attualità. Ammonisce contro ogni forma di totalitarismo, di falsificazione della realtà e della storia, corrotta dai mezzi d''informazione, e contro l''annullamento dell''identità individuale. Significativa è la traduzione italiana di "Big Brother" (fratello maggiore) che ormai è rimasta nel nostro immaginario come quella di "Grande Fratello".', '1948', '320');
INSERT INTO books (title, author, image, summary, year, pages) VALUES ('La Divina Commedia', 'Dante Alighieri', 'divina_commedia.jpg', 'L’opera è divisa in tre parti: Inferno, Purgatorio e Paradiso, ciascuna composta di trentatré canti. Ad accompagnare Dante nella straordinaria discesa all’Inferno e nella salita al Purgatorio è il poeta latino Virgilio, che riveste il ruolo di guida spirituale. I personaggi che i due incontrano nei gironi infernali, dannati dalle colpe sempre più gravi, appartengono non solo alla storia e alla mitologia, ma sono anche contemporanei dell’autore, che non esita a condannare i mali del tempo, e in particolare la corruzione di clero e papato. Per questo motivo La Divina Commedia è considerata anche un’opera politica. Nel Purgatorio, rappresentato come una montagna, si trovano invece coloro che nel corso della vita compirono peccati più lievi; per questo l’atmosfera è più serena, intrisa di speranza, e anche l’anima di Dante, nel corso della salita, si alleggerisce del peso delle sue colpe. Nel Paradiso Dante incontra l’amata Beatrice, che lo conduce attraverso i cieli dei pianeti e delle stelle fisse, tra angeli, santi e beati, fino al cospetto di Dio, in un crescendo di luminosità e di purificazione.', '1300', '1000');
INSERT INTO books (title, author, image, summary, year, pages) VALUES ('Il Grande Gatsby', 'Francis Scott Fitzgerald', 'The_Great_Gatsby.jpg', 'Il romantico ed enigmatico Jay Gatsby organizza feste sontuose nella speranza di avvicinare la donna amata in gioventù, Daisy, che ha sposato un uomo ricco e rozzo. Ne diventerà l''amante, ma un incidente automobilistico darà una tragica svolta al loro amore. Una descrizione spietata e partecipe del mondo fastoso e frivolo degli anni Venti nelle pagine indimenticabili dello scrittore simbolo della generazione perduta.', '1925', '400 ');



INSERT INTO users_books (user_id, book_id, read) VALUES (1, 1, true);
INSERT INTO users_books (user_id, book_id, read) VALUES (1, 2, true);
INSERT INTO users_books (user_id, book_id, read) VALUES (1, 3, false);